
name: cont_int

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'
          
      - name: Run tests
        run: pytest --cov=life_expectancy
        
      - name: Run pylint
        run: pylint life_expectancy.cleaning
